robot_simulation:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: j1
    pid_gains: {p: 1.0, i: 0.0, d: 1.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: j2
    pid_gains: {p: 1.0, i: 0.0, d: 1.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: j3
    pid_gains: {p: 1.0, i: 0.0, d: 1.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: j4
    pid_gains: {p: 1.0, i: 0.0, d: 1.0}